name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/nbkey1"
      - run: chmod 600 "$HOME/.ssh/nbkey1"
      # Deploy
      - run: rsync -e "ssh -p 22 -i $HOME/.ssh/nbkey1 -o StrictHostKeyChecking=no" --archive --compress --delete . valerij@213.136.82.58:/home/www/bmax-dev.osomcrm.com